### ISSUE TITLE
Mongoose Connection Error

### ISSUE THREAD

**Issue by ternalify** [merzainc/vidly-api#1]
I'm followed the procedures but getting mongooseserverselectionerror: connect econnrefused 127.0. 0.1:27017 error. Using Linux Ubuntu.

**Comment by merzainc** [comment]
1. Make sure you've started MongoDB daemon using `sudo service mongod start`.
2. Lastly makesure to use 127.0.0.1 instead of localhost in the connection string when using mongoose. If the problem still persist please check your installation. I encourage you to provide more details about the error.
